test_that("autotest", {
  set.seed(1)
  # set low value for min obs b/c of small n in autogenerated tasks
  learner = lrn("surv.priority_lasso",
                blocks=list(block1=1:13,block2=14:80, block3=81:190))
  expect_learner(learner)
  expect_error(learner$selected_features(), "No model stored")

  data = data.frame(matrix(rnorm(50*190),50,190),
                    time = runif(50, 0, 100),
                    status = rbinom(50, 1, 0.5))
  task = as_task_surv(data, id = "right_censored",
                      time = "time", event = "status", type = "right")
  learner$train(task)$selected_features()
})
