install_learners("surv.gbm")
load_tests("surv.gbm")

test_that("autotest", {
  set.seed(1)
  # set low value for min obs b/c of small n in autogenerated tasks
  learner = lrn("surv.gbm", id = "gbm", n.minobsinnode = 1L, n.trees = 100L)
  expect_learner(learner)
  result = run_autotest(learner, check_replicable = FALSE)
  expect_true(result, info = result$error)
  expect_error(learner$importance(), "No model stored")
  learner$train(tsk("rats"))$importance()
})

test_that("surv.gbm", {
  learner = lrn("surv.gbm")
  fun = fun_list = list(gbm::gbm, gbm::predict.gbm)
  exclude = c(
    "formula", # handled by mlr3
    "data", # handled by mlr3
    "weights", # handled by mlr3
    "class.stratify.cv", # handled by mlr3
    "single.tree", # we don't allow for single trees
    "newdata", # handled by mlr3
    "object", # handled by mlr3
    "type" # we only allow type "link" to get the response prediction
  )

  param_test = run_paramtest(learner, fun_list, exclude)
  expect_true(param_test)
})
