---
title: "mlr3verse learners"
output: html_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  cache = FALSE,
  collapse = TRUE,
  comment = "#>",
  echo = TRUE
)
install.packages("DT")
```

```{r,echo=FALSE}
d = mlr3extralearners::list_mlr3learners()
d$required_packages = sapply(d$required_packages, function(x) paste0(setdiff(x, c("mlr3", "mlr3extralearners")), collapse = "\n"))
d$properties = sapply(d$properties, paste0, collapse = "\n")
d$feature_types = sapply(d$feature_types, paste0, collapse = "\n")
d$predict_types = sapply(d$predict_types, paste0, collapse = "\n")
d$name = mlr3misc::pmap(list(d[["name"]], d[["mlr3_package"]], d[["id"]]), function(name, pkg, id) {
  url = sprintf("https://%s.mlr-org.com/reference/mlr_learners_%s.html",
    pkg, id)
  paste0("<a href=\"", url, "\">", name, "</a>")
})

DT::datatable(d, filter = "top",
  options = list(pageLength = nrow(d)),
  colnames = c("Name", "Class", "ID", "mlr3 Package",
    "Packages", "Properties",
    "Feature Types", "Predict Types"),
  escape = FALSE
)
```
