bibentries = c( # nolint start

  finegray1999crr = bibentry("article",
    author = "Fine, Jason P. and Gray, Robert J.",
    title = "A proportional hazards model for the subdistribution of a competing risk",
    journal = "Journal of the American Statistical Association",
    volume = 94,
    number = 446,
    year = 1999,
    pages = "496--509"
  ),

  breiman_2001 = bibentry("article",
    title       = "Random Forests",
    author      = "Breiman, Leo",
    year        = "2001",
    journal     = "Machine Learning",
    volume      = "45",
    number      = "1",
    pages       = "5--32",
    doi         = "10.1023/A:1010933404324",
    issn        = "1573-0565"
  ),

  ishwaran_2008 = bibentry("article",
    doi         = "10.1214/08-aoas169",
    url         = "https://doi.org/10.1214/08-aoas169",
    year        = "2008",
    month       = "9",
    publisher   = "Institute of Mathematical Statistics",
    volume      = "2",
    number      = "3",
    author      = "Hemant Ishwaran and Udaya B. Kogalur and Eugene H. Blackstone and Michael S. Lauer",
    title       = "Random survival forests",
    journal     = "The Annals of Applied Statistics"
  ),

  hiabu_2023 = bibentry("article",
    title   = "Random Planted Forest: a directly interpretable tree ensemble",
    author  = "Hiabu, Munir and Mammen, Enno and Meyer, Joseph T.",
    journal = "arXiv preprint arXiv:2012.14563",
    doi     = "10.48550/ARXIV.2012.14563",
    year    = "2023"
  ),

  hothorn_2015 = bibentry("article",
    author      = "Torsten Hothorn and Achim Zeileis",
    title       = "partykit: A Modular Toolkit for Recursive Partytioning in R",
    journal     = "Journal of Machine Learning Research",
    year        = "2015",
    volume      = "16",
    number      = "118",
    pages       = "3905-3909",
    url         = "http://jmlr.org/papers/v16/hothorn15a.html"
  ),

  hothorn_2006 = bibentry("article",
    doi         = "10.1198/106186006x133933",
    url         = "https://doi.org/10.1198/106186006x133933",
    year        = "2006",
    month       = "9",
    publisher   = "Informa {UK} Limited",
    volume      = "15",
    number      = "3",
    pages       = "651--674",
    author      = "Torsten Hothorn and Kurt Hornik and Achim Zeileis",
    title       = "Unbiased Recursive Partitioning: A Conditional Inference Framework",
    journal     = "Journal of Computational and Graphical Statistics"
  ),

  jaeger_2019 = bibentry("article",
    doi           = "10.1214/19-aoas1261",
    year          = "2019",
    month         = "9",
    publisher     = "Institute of Mathematical Statistics",
    volume        = "13",
    number        = "3",
    author        = "Byron C. Jaeger and D. Leann Long and Dustin M. Long and Mario Sims and Jeff M. Szychowski and Yuan-I Min and Leslie A. Mcclure and George Howard and Noah Simon",
    title         = "Oblique random survival forests",
    journal       = "The Annals of Applied Statistics"
  ),

  jaeger_2022 = bibentry("article",
    title         = "Accelerated and interpretable oblique random survival forests",
    author        = "Byron C. Jaeger and Sawyer Welden and Kristin Lenoir and Jaime L. Speiser and Matthew W. Segar and Ambarish Pandey and Nicholas M. Pajewski",
    journal       = "Journal of Computational and Graphical Statistics",
    doi           = "10.1080/10618600.2023.2231048",
    year          = "2023",
    month         = "8",
    publisher     = "Taylor & Francis",
    pages         = "1--16"
  ),

  dorogush2018catboost = bibentry("article",
    title = "CatBoost: gradient boosting with categorical features support",
    author = "Dorogush, Anna Veronika and Ershov, Vasily and Gulin, Andrey",
    journal = "arXiv preprint arXiv:1810.11363",
    year = "2018"
  ),

  binder2009boosting = bibentry("article",
    title = "Boosting for high-dimensional time-to-event data with competing risks",
    author = "Binder, Harald and Allignol, Arthur and Schumacher, Martin and Beyersmann, Jan",
    journal = "Bioinformatics",
    volume = "25",
    number = "7",
    pages = "890--896",
    year = "2009",
    publisher = "Oxford University Press"
  ),

  quinlan2014c4 = bibentry("book",
    title = "C4. 5: programs for machine learning",
    author = "Quinlan, J Ross",
    year = "2014",
    publisher = "Elsevier"
  ),

  quinlan1992learning = bibentry("inproceedings",
    title = "Learning with continuous classes",
    author = "Quinlan, John R and others",
    booktitle = "5th Australian joint conference on artificial intelligence",
    volume = "92",
    pages = "343--348",
    year = "1992",
    organization = "World Scientific"
  ),

  boltz2007knn = bibentry("inproceedings",
    title = "kNN-based high-dimensional Kullback-Leibler distance for tracking",
    author = "Boltz, Sylvain and Debreuve, Eric and Barlaud, Michel",
    booktitle = "Eighth International Workshop on Image Analysis for Multimedia Interactive Services (WIAMIS'07)",
    pages = "16--16",
    year = "2007",
    organization = "IEEE"
  ),

  sparapani2021nonparametric = bibentry("article",
    title = "Nonparametric machine learning and efficient computation with bayesian additive regression trees: the BART R package",
    author = "Sparapani, Rodney and Spanbauer, Charles and McCulloch, Robert",
    journal = "Journal of Statistical Software",
    volume = "97",
    pages = "1--66",
    year = "2021"
  ),


  quinlan1993combining = bibentry("inproceedings",
    title = "Combining instance-based and model-based learning",
    author = "Quinlan, J Ross",
    booktitle = "Proceedings of the tenth international conference on machine learning",
    pages = "236--243",
    year = "1993"
  ),

  milborrow2014earth = bibentry("article",
    title = "Earth: multivariate adaptive regression spline models",
    author = "Milborrow, Stephen and Hastie, T and Tibshirani, R",
    journal = "R package version",
    volume = "3",
    number = "7",
    year = "2014"
  ),
  friedman1991multivariate = bibentry("article",
    title = "Multivariate adaptive regression splines",
    author = "Friedman, Jerome H",
    journal = "The annals of statistics",
    volume = "19",
    number = "1",
    pages = "1--67",
    year = "1991",
    publisher = "Institute of Mathematical Statistics"
  ),
  geurts2006extremely = bibentry("article",
    title = "Extremely randomized trees",
    author = "Geurts, Pierre and Ernst, Damien and Wehenkel, Louis",
    journal = "Machine learning",
    volume = "63",
    number = "1",
    pages = "3--42",
    year = "2006",
    publisher = "Springer"
  ),
  royston2002flexible = bibentry("article",
    title = "Flexible parametric proportional-hazards and proportional-odds models for censored survival data, with application to prognostic modelling and estimation of treatment effects",
    author = "Royston, Patrick and Parmar, Mahesh KB",
    journal = "Statistics in medicine",
    volume = "21",
    number = "15",
    pages = "2175--2197",
    year = "2002",
    publisher = "Wiley Online Library"
  ),
  friedman2002stochastic = bibentry("article",
    title = "Stochastic gradient boosting",
    author = "Friedman, Jerome H",
    journal = "Computational statistics & data analysis",
    volume = "38",
    number = "4",
    pages = "367--378",
    year = "2002",
    publisher = "Elsevier"
  ),
  gu2003penalized = bibentry("article",
    title = "Penalized likelihood density estimation: Direct cross-validation and scalable approximation",
    author = "Gu, Chong and Wang, Jingyuan",
    journal = "Statistica Sinica",
    pages = "811--826",
    year = "2003",
    publisher = "JSTOR"
  ),
  quintela2012nonparametric = bibentry("article",
    title = "Nonparametric kernel distribution function estimation with kerdiest: an R package for bandwidth choice and applications",
    author = "Quintela-del-R\xc3\xado, Alejandro, and Graciela Est\xc3\xa9vez-P\xc3\xa9rez",
    journal = "Journal of Statistical Software",
    volume = "50",
    pages = "1--21",
    year = "2012"
  ),
  karatzoglou2004kernlab = bibentry("article",
    title = "kernlab-an S4 package for kernel methods in R",
    author = "Karatzoglou, Alexandros and Smola, Alex and Hornik, Kurt and Zeileis, Achim",
    journal = "Journal of statistical software",
    volume = "11",
    number = "9",
    pages = "1--20",
    year = "2004",
    publisher = "American Statistical Association"
  ),
  gramacki2017fft = bibentry("article",
    title = "FFT-based fast computation of multivariate kernel density estimators with unconstrained bandwidth matrices",
    author = "Gramacki, Artur and Gramacki, Jaros\xc5\x82aw",
    journal = "Journal of Computational and Graphical Statistics",
    volume = "26",
    number = "2",
    pages = "459--462",
    year = "2017",
    publisher = "Taylor & Francis"
  ),
  fan2008liblinear = bibentry("article",
    title = "LIBLINEAR: A library for large linear classification",
    author = "Fan, Rong-En and Chang, Kai-Wei and Hsieh, Cho-Jui and Wang, Xiang-Rui and Lin, Chih-Jen",
    journal = "the Journal of machine Learning research",
    volume = "9",
    pages = "1871--1874",
    year = "2008",
    publisher = "JMLR. org"
  ),
  ke2017lightgbm = bibentry("article",
    title = "Lightgbm: A highly efficient gradient boosting decision tree",
    author = "Ke, Guolin and Meng, Qi and Finley, Thomas and Wang, Taifeng and Chen, Wei and Ma, Weidong and Ye, Qiwei and Liu, Tie-Yan",
    journal = "Advances in neural information processing systems",
    volume = "30",
    year = "2017"
  ),
  loader2006local = bibentry("book",
    title = "Local regression and likelihood",
    author = "Loader, Clive",
    year = "2006",
    publisher = "Springer Science & Business Media"
  ),
  kooperberg1992logspline = bibentry("article",
    title = "Logspline density estimation for censored data",
    author = "Kooperberg, Charles and Stone, Charles J",
    journal = "Journal of Computational and Graphical Statistics",
    volume = "1",
    number = "4",
    pages = "301--328",
    year = "1992",
    publisher = "Taylor & Francis"
  ),
  buhlmann2003boosting = bibentry("article",
    title = "Boosting with the L 2 loss: regression and classification",
    author = "B\xc3\xbchlmann, Peter and Yu, Bin",
    journal = "Journal of the American Statistical Association",
    volume = "98",
    number = "462",
    pages = "324--339",
    year = "2003",
    publisher = "Taylor & Francis"
  ),
  hastie2017generalized = bibentry("book",
    title = "Generalized additive models",
    author = "Hastie, Trevor J and Tibshirani, Robert J",
    year = "2017",
    publisher = "Routledge"
  ),
  wood2012mgcv = bibentry("misc",
    title = "mgcv: Mixed GAM Computation Vehicle with GCV/AIC/REML smoothness estimation",
    author = "Wood, Simon",
    year = "2012"
  ),
  li2003nonparametric = bibentry("article",
    title = "Nonparametric estimation of distributions with categorical and continuous data",
    author = "Li, Qi and Racine, Jeff",
    journal = "journal of multivariate analysis",
    volume = "86",
    number = "2",
    pages = "266--292",
    year = "2003",
    publisher = "Elsevier"
  ),
  goeman2010l1 = bibentry("article",
    title = "L1 penalized estimation in the Cox proportional hazards model",
    author = "Goeman, Jelle J",
    journal = "Biometrical journal",
    volume = "52",
    number = "1",
    pages = "70--84",
    year = "2010",
    publisher = "Wiley Online Library"
  ),
  schellhase2012density = bibentry("article",
    title = "Density estimation and comparison with a penalized mixture approach",
    author = "Schellhase, Christian and Kauermann, G\xc3\xb6ran",
    journal = "Computational Statistics",
    volume = "27",
    number = "4",
    pages = "757--777",
    year = "2012",
    publisher = "Springer"
  ),
  engel1994iterative = bibentry("article",
    title = "An iterative bandwidth selector for kernel estimation of densities and their derivatives",
    author = "Engel, Joachim and Herrmann, Eva and Gasser, Theo",
    journal = "Journaltitle of Nonparametric Statistics",
    volume = "4",
    number = "1",
    pages = "21--34",
    year = "1994",
    publisher = "Taylor & Francis"
  ),
  freund1996experiments = bibentry("inproceedings",
    title = "Experiments with a new boosting algorithm",
    author = "Freund, Yoav and Schapire, Robert E and others",
    booktitle = "icml",
    volume = "96",
    pages = "148--156",
    year = "1996",
    organization = "Citeseer"
  ),
  aha1991instance = bibentry("article",
    title = "Instance-based learning algorithms",
    author = "Aha, David W and Kibler, Dennis and Albert, Marc K",
    journal = "Machine learning",
    volume = "6",
    number = "1",
    pages = "37--66",
    year = "1991",
    publisher = "Springer"
  ),
  cohen1995fast = bibentry("incollection",
    title = "Fast effective rule induction",
    author = "Cohen, William W",
    booktitle = "Machine learning proceedings 1995",
    pages = "115--123",
    year = "1995",
    publisher = "Elsevier"
  ),
  landwehr2005logistic = bibentry("article",
    title = "Logistic model trees",
    author = "Landwehr, Niels and Hall, Mark and Frank, Eibe",
    journal = "Machine learning",
    volume = "59",
    number = "1",
    pages = "161--205",
    year = "2005",
    publisher = "Springer"
  ),
  holte1993very = bibentry("article",
    title = "Very simple classification rules perform well on most commonly used datasets",
    author = "Holte, Robert C",
    journal = "Machine learning",
    volume = "11",
    number = "1",
    pages = "63--90",
    year = "1993",
    publisher = "Springer"
  ),
  frank1998generating = bibentry("misc",
    title = "Generating accurate rule sets without global optimization",
    author = "Frank, Eibe and Witten, Ian H",
    year = "1998",
    publisher = "University of Waikato, Department of Computer Science"
  ),
  holmes1999generating = bibentry("inproceedings",
    title = "Generating rule sets from model trees",
    author = "Holmes, Geoffrey and Hall, Mark and Prank, Eibe",
    booktitle = "Australasian joint conference on artificial intelligence",
    pages = "1--12",
    year = "1999",
    organization = "Springer"
  ),
  bowman1997applied = bibentry("book",
    title = "Applied Smoothing Techniques for Data Analysis: The Kernel Approach with S-Plus Illustrations",
    author = "Bowman, A.W. and Azzalini, A.",
    isbn = "9780191545696",
    series = "Oxford Statistical Science Series",
    url = "https://books.google.de/books?id=7WBMrZ9umRYC",
    year = "1997",
    publisher = "OUP Oxford"
  ),
  hosmer2013applied = bibentry("book",
    title = "Applied logistic regression",
    author = "Hosmer Jr, David W and Lemeshow, Stanley and Sturdivant, Rodney X",
    volume = "398",
    year = "2013",
    publisher = "John Wiley & Sons"
  ),
  nelson1969hazard = bibentry("article",
    title = "Hazard plotting for incomplete failure data",
    author = "Nelson, Wayne",
    journal = "Journal of Quality Technology",
    volume = "1",
    number = "1",
    pages = "27--52",
    year = "1969",
    publisher = "Taylor & Francis"
  ),
  nelson1972theory = bibentry("article",
    title = "Theory and applications of hazard plotting for censored failure data",
    author = "Nelson, Wayne",
    journal = "Technometrics",
    volume = "14",
    number = "4",
    pages = "945--966",
    year = "1972",
    publisher = "Taylor & Francis"
  ),
  aalen1978nonparametric = bibentry("article",
    title = "Nonparametric inference for a family of counting processes",
    author = "Aalen, Odd",
    journal = "The Annals of Statistics",
    pages = "701--726",
    year = "1978",
    publisher = "JSTOR"
  ),
  kalbfleisch2011statistical = bibentry("book",
    title = "The statistical analysis of failure time data",
    author = "Kalbfleisch, John D and Prentice, Ross L",
    year = "2011",
    publisher = "John Wiley & Sons"
  ),
  akritas1994nearest = bibentry("article",
    title = "Nearest neighbor estimation of a bivariate distribution under random censoring",
    author = "Akritas, Michael G",
    journal = "The Annals of Statistics",
    pages = "1299--1327",
    year = "1994",
    publisher = "JSTOR"
  ),
  kvamme2019time = bibentry("article",
    title = "Time-to-event prediction with neural networks and Cox regression",
    author = "Kvamme, H\xc3\xa5vard, \xc3\x98rnulf Borgan, and Ida Scheel",
    journal = "arXiv preprint arXiv:1907.00825",
    year = "2019"
  ),
  lee2018deephit = bibentry("inproceedings",
    title = "Deephit: A deep learning approach to survival analysis with competing risks",
    author = "Lee, Changhee and Zame, William and Yoon, Jinsung and Van Der Schaar, Mihaela",
    booktitle = "Proceedings of the AAAI conference on artificial intelligence",
    volume = "32",
    number = "1",
    year = "2018"
  ),
  katzman2018deepsurv = bibentry("article",
    title = "DeepSurv: personalized treatment recommender system using a Cox proportional hazards deep neural network",
    author = "Katzman, Jared L and Shaham, Uri and Cloninger, Alexander and Bates, Jonathan and Jiang, Tingting and Kluger, Yuval",
    journal = "BMC medical research methodology",
    volume = "18",
    number = "1",
    pages = "1--12",
    year = "2018",
    publisher = "BioMed Central"
  ),
  zhao2019dnnsurv = bibentry("article",
    title = "Dnnsurv: Deep neural networks for survival analysis using pseudo values",
    author = "Zhao, Lili and Feng, Dai",
    journal = "arXiv preprint arXiv:1908.02337",
    year = "2019"
  ),
  gensheimer2018simple = bibentry("article",
    title = "Simple discrete-time survival model for neural networks",
    author = "Gensheimer, Michael F and Narasimhan, BA",
    journal = "arXiv",
    year = "2018"
  ),
  kvamme2019continuous = bibentry("article",
    title = "Continuous and discrete-time survival prediction with neural networks",
    author = "Kvamme, H\xc3\xa5vard, and \xc3\x98rnulf Borgan",
    journal = "arXiv preprint arXiv:1910.06724",
    year = "2019"
  ),
  van2011improved = bibentry("article",
    title = "Improved performance on high-dimensional survival data by application of Survival-SVM",
    author = "Van Belle, Vanya and Pelckmans, Kristiaan and Van Huffel, Sabine and Suykens, Johan AK",
    journal = "Bioinformatics",
    volume = "27",
    number = "1",
    pages = "87--94",
    year = "2011",
    publisher = "Oxford University Press"
  ),

  van2011support = bibentry("article",
    title = "Support vector methods for survival analysis: a comparison between ranking and regression approaches",
    author = "Van Belle, Vanya and Pelckmans, Kristiaan and Van Huffel, Sabine and Suykens, Johan AK",
    journal = "Artificial intelligence in medicine",
    volume = "53",
    number = "2",
    pages = "107--118",
    year = "2011",
    publisher = "Elsevier"
  ),
  shivaswamy2007support = bibentry("inproceedings",
    title = "A support vector approach to censored targets",
    author = "Shivaswamy, Pannagadatta K and Chu, Wei and Jansche, Martin",
    booktitle = "Seventh IEEE international conference on data mining (ICDM 2007)",
    pages = "655--660",
    year = "2007",
    organization = "IEEE"
  ),
  friedman_2010 = bibentry("article",
    title            = "Regularization Paths for Generalized Linear Models via Coordinate Descent",
    author           = "Jerome Friedman and Trevor Hastie and Robert Tibshirani",
    year             = "2010",
    journal          = "Journal of Statistical Software",
    volume           = "33",
    number           = "1",
    pages            = "1--22",
    doi              = "10.18637/jss.v033.i01"
  ),
  wright_2017 = bibentry("article",
    title            = "{ranger}: A Fast Implementation of Random Forests for High Dimensional Data in {C++} and {R}",
    author           = "Wright, Marvin N. and Ziegler, Andreas",
    year             = "2017",
    journal          = "Journal of Statistical Software",
    volume           = "77",
    number           = "1",
    pages            = "1--17",
    doi              = "10.18637/jss.v077.i01"
  ),
  chen_2016 = bibentry("inproceedings",
    title            = "Xgboost: A scalable tree boosting system",
    author           = "Chen, Tianqi and Guestrin, Carlos",
    year             = "2016",
    booktitle        = "Proceedings of the 22nd ACM SIGKDD Conference on Knowledge Discovery and Data Mining",
    pages            = "785--794",
    doi              = "10.1145/2939672.2939785",
    organization     = "ACM"
  ),
  chipman2010bart = bibentry("article",
    title = "BART: Bayesian additive regression trees",
    author = "Chipman, Hugh A and George, Edward I and McCulloch, Robert E",
    journal = "The Annals of Applied Statistics",
    volume = "4",
    number = "1",
    pages = "266--298",
    year = "2010",
    publisher = "Institute of Mathematical Statistics"
  ),
  bates2010lme4 = bibentry("misc",
    title = "lme4: Mixed-effects modeling with R",
    author = "Bates, Douglas M",
    year = "2010",
    publisher = "Springer New York"
  ),
  lenth2010response = bibentry("article",
    title = "Response-surface methods in R, using rsm",
    author = "Lenth, Russell V",
    journal = "Journal of Statistical Software",
    volume = "32",
    pages = "1--17",
    year = "2010"
  ),
  klau2018priolasso = bibentry("article",
    title = "Priority-Lasso: a simple hierarchical approach to the prediction of clinical outcome using multi-omics data",
    author = "Klau Simon, Jurinovic Vindi, Hornung Roman, Herold Tobias, Boulesteix Anne-Laure",
    journal = "BMC Bioinformatics",
    volume = "19",
    year = "2018",
    doi = "10.1186/s12859-018-2344-6"
  ),
  obrien2019imbrfsrc = bibentry("article",
    title = "A random forests quantile classifier for class imbalanced data",
    author = "Robert O\xe2\x80\x99Brien and Hemant Ishwaran",
    journal = "Pattern Recognition",
    volume = "90",
    pages = "232--249",
    year = "2019",
    doi = "10.1016/j.patcog.2019.01.036"
  ),
  chen2004imbrf = bibentry("article",
    title = "Using Random Forest to Learn Imbalanced Data",
    author = "Chen Chao and Breiman Leo",
    year = "2004",
    month = "01",
    journal = "University of California, Berkeley"
  ),
  barnwal2022 = bibentry("article",
    title = "Survival Regression with Accelerated Failure Time Model in XGBoost",
    author = "Barnwal Avinash, Cho Hyunsu and Hocking Toby",
    doi = "10.1080/10618600.2022.2067548",
    issn = "15372715",
    journal = "Journal of Computational and Graphical Statistics",
    publisher = "American Statistical Association",
    year = "2022"
  ),
  Kohavi1995 = bibentry("inproceedings",
    author = "Ron Kohavi",
    booktitle = "8th European Conference on Machine Learning",
    pages = "174--189",
    publisher = "Springer",
    title = "The Power of Decision Tables",
    year = "1995"
  ),
  Cleary1995 = bibentry("inproceedings",
    author = "John G. Cleary and Leonard E. Trigg",
    booktitle = "12th International Conference on Machine Learning",
    pages = "108-114",
    title = "K*: An Instance-based Learner Using an Entropic Distance Measure",
    year = "1995"
  ),
  Quinlan1992 = bibentry("inproceedings",
    address = "Singapore",
    author = "Ross J. Quinlan",
    booktitle = "5th Australian Joint Conference on Artificial Intelligence",
    pages = "343-348",
    publisher = "World Scientific",
    title = "Learning with Continuous Classes",
    year = "1992"
  ),
  Wang1997 = bibentry("inproceedings",
    author = "Y. Wang and I. H. Witten",
    booktitle = "Poster papers of the 9th European Conference on Machine Learning",
    publisher = "Springer",
    title = "Induction of model trees for predicting continuous classes",
    year = "1997"
  ),
  Mackay1998 = bibentry("misc",
    address = "Dept. of Physics, Cambridge University, UK",
    author = "David J.C. Mackay",
    title = "Introduction to Gaussian Processes",
    year = "1998",
    PS = "http://wol.ra.phy.cam.ac.uk/mackay/gpB.ps.gz"
  ),
  leCessie1992 = bibentry("article",
    author = "le Cessie, S. and van Houwelingen, J.C.",
    journal = "Applied Statistics",
    number = "1",
    pages = "191-201",
    title = "Ridge Estimators in Logistic Regression",
    volume = "41",
    year = "1992"
  ),
  John1995 = bibentry("inproceedings",
    address = "San Mateo",
    author = "George H. John and Pat Langley",
    booktitle = "Eleventh Conference on Uncertainty in Artificial Intelligence",
    pages = "338-345",
    publisher = "Morgan Kaufmann",
    title = "Estimating Continuous Distributions in Bayesian Classifiers",
    year = "1995"
  ),
  Mccallum1998 = bibentry("inproceedings",
    author = "Andrew Mccallum and Kamal Nigam",
    booktitle = "AAAI-98 Workshop on 'Learning for Text Categorization'",
    title = "A Comparison of Event Models for Naive Bayes Text Classification",
    year = "1998"
  ),
  Sumner2005 = bibentry("inproceedings",
    author = "Marc Sumner and Eibe Frank and Mark Hall",
    booktitle = "9th European Conference on Principles and Practice of Knowledge Discovery in Databases",
    pages = "675-683",
    publisher = "Springer",
    title = "Speeding up Logistic Model Tree Induction",
    year = 2005
  ),
  Platt1998 = bibentry("incollection",
    author = "J. Platt",
    booktitle = "Advances in Kernel Methods - Support Vector Learning",
    editor = "B. Schoelkopf and C. Burges and A. Smola",
    publisher = "MIT Press",
    title = "Fast Training of Support Vector Machines using Sequential Minimal Optimization",
    year = "1998",
    URL = "http://research.microsoft.com/jplatt/smo.html",
    PS = "http://research.microsoft.com/jplatt/smo-book.ps.gz",
    PDF = "http://research.microsoft.com/jplatt/smo-book.pdf"
  ),
  Keerthi2001 = bibentry("article",
    author = "S.S. Keerthi and S.K. Shevade and C. Bhattacharyya and K.R.K. Murthy",
    journal = "Neural Computation",
    number = "3",
    pages = "637-649",
    title = "Improvements to Platt's SMO Algorithm for SVM Classifier Design",
    volume = "13",
    year = "2001",
    PS = "http://guppy.mpe.nus.edu.sg/mpessk/svm/smo_mod_nc.ps.gz"
  ),
  Hastie1998 = bibentry("inproceedings",
    author = "Trevor Hastie and Robert Tibshirani",
    booktitle = "Advances in Neural Information Processing Systems",
    editor = "Michael I. Jordan and Michael J. Kearns and Sara A. Solla",
    publisher = "MIT Press",
    title = "Classification by Pairwise Coupling",
    volume = "10",
    year = "1998",
    PS = "http://www-stat.stanford.edu/hastie/Papers/2class.ps"
  ),
  Shevade1999 = bibentry("inproceedings",
    author = "S.K. Shevade and S.S. Keerthi and C. Bhattacharyya and K.R.K. Murthy",
    booktitle = "IEEE Transactions on Neural Networks",
    title = "Improvements to the SMO Algorithm for SVM Regression",
    year = "1999",
    PS = "http://guppy.mpe.nus.edu.sg/mpessk/svm/ieee_smo_reg.ps.gz"
  ),
  Freund1998 = bibentry("inproceedings",
    address = "New York, NY",
    author = "Y. Freund and R. E. Schapire",
    booktitle = "11th Annual Conference on Computational Learning Theory",
    pages = "209-217",
    publisher = "ACM Press",
    title = "Large margin classification using the perceptron algorithm",
    year = "1998"
  ),
  Dudoit2002 = bibentry("article",
    title = "Comparison of Discrimination Methods for the Classification of Tumors Using Gene Expression Data",
    author = "Sandrine Dudoit and Jane Fridlyand and Terence P Speed",
    year = "2002",
    journal = "Journal of the American Statistical Association",
    volume = "97",
    number = "457",
    pages = "77--87",
    publisher = "ASA Websites",
    doi = "10.1198/016214502753479248"
  ),
  Srivastava2007mdeb = bibentry("article",
    title = "Comparison of Discrimination Methods for High Dimensional Data",
    author = "Srivastava, M. and Kubokawa, T.",
    year = "2007",
    journal = "Journal of the Japanese Statistical Association",
    volume = "37",
    number = "1",
    pages = "123--134"
  ),
  Peng2009sdlda = bibentry("article",
    ISSN = "0006341X, 15410420",
    URL = "http://www.jstor.org/stable/20640622",
    abstract = "High-dimensional data such as microarrays have brought us new statistical challenges. For example, using a large number of genes to classify samples based on a small number of microarrays remains a difficult problem. Diagonal discriminant analysis, support vector machines, and k-nearest neighbor have been suggested as among the best methods for small sample size situations, but none was found to be superior to others. In this article, we propose an improved diagonal discriminant approach through shrinkage and regularization of the variances. The performance of our new approach along with the existing methods is studied through simulations and applications to real data. These studies show that the proposed shrinkage-based and regularization diagonal discriminant methods have lower misclassification rates than existing methods in many cases.",
    author = "Herbert Pang and Tiejun Tong and Hongyu Zhao",
    journal = "Biometrics",
    number = "4",
    pages = "1021--1029",
    publisher = "[Wiley, International Biometric Society]",
    title = "Shrinkage-Based Diagonal Discriminant Analysis and Its Applications in High-Dimensional Data",
    urldate = "2025-05-21",
    volume = "65",
    year = "2009"
  ),
  friedman1989rda = bibentry("article",
   ISSN = "01621459, 1537274X",
   URL = "http://www.jstor.org/stable/2289860",
   author = "Jerome H. Friedman",
   journal = "Journal of the American Statistical Association",
   number = "405",
   pages = "165--175",
   publisher = "American Statistical Association, Taylor & Francis, Ltd.",
   title = "Regularized Discriminant Analysis",
   volume = "84",
   year = "1989"
  ),
  ahdesmaki2010sda = bibentry("article",
    title="Feature selection in omics prediction problems using cat scores and false nondiscovery rate control",
    volume="4",
    ISSN="1932-6157",
    url="http://dx.doi.org/10.1214/09-AOAS277",
    DOI="10.1214/09-aoas277",
    number="1",
    journal="The Annals of Applied Statistics",
    publisher="Institute of Mathematical Statistics",
    author="Ahdesmaeki, Miika and Strimmer, Korbinian",
    year="2010",
    month="03"
  ),
  faisolo2017qgam = bibentry("article",
    title = "Fast Calibrated Additive Quantile Regression",
    author = "Fasiolo, Matteo and Wood, Simon N. and Zaffran, Margaux and Nedellec, Raphael and Goude, Yannig",
    year = "2017",
    journal = "Journal of the American Statistical Association",
    volume = "116",
    pages = "1402--1412",
    doi = "10.1080/01621459.2020.1725521"
  ),
  howard_2020 = bibentry("article",
    title     = "Fastai: A Layered API for Deep Learning",
    author    = "Howard, Jeremy and Gugger, Sylvain",
    year      = "2020",
    journal   = "Information",
    volume    = "11",
    number    = "2",
    pages     = "108",
    doi       = "10.3390/info11020108",
    issn      = "2078-2489",
    publisher = "MDPI AG",
    month     = "feb"
  ),
  hollmann2025tabpfn = bibentry("article",
    title = "Accurate predictions on small data with a tabular foundation model",
    author = "Hollmann, Noah and M\xc3\xbcller, Samuel and Purucker, Lennart and
         Krishnakumar, Arjun and K\xc3\xb6rfer, Max and Hoo, Shi Bin and
         Schirrmeister, Robin Tibor and Hutter, Frank",
    journal = "Nature",
    year = "2025",
    month = "01",
    day = "09",
    doi = "10.1038/s41586-024-08328-6",
    publisher = "Springer Nature",
    URL = "https://www.nature.com/articles/s41586-024-08328-6"
  ),
  hollmann2023tabpfn = bibentry("inproceedings",
    title = "TabPFN: A transformer that solves small tabular classification problems in a second",
    author = "Hollmann, Noah and M\xc3\xbcller, Samuel and Eggensperger, Katharina and Hutter, Frank",
    booktitle = "International Conference on Learning Representations 2023",
    year = "2023"
  ),
  knn2002 = bibentry("book",
    title = "Modern Applied Statistics with S",
    author = "W. N. Venables and B. D. Ripley",
    publisher = "Springer",
    edition = "Fourth",
    address = "New York",
    year = "2002",
    note = "ISBN 0-387-95457-0",
    url = "https://www.stats.ox.ac.uk/pub/MASS4/"
  ),
  hornung2019blockforest = bibentry("article",
    title = "Block Forests: Random forests for blocks of clinical and omics covariate data",
    author = "Hornung, R. and Wright, M. N.",
    journal = "BMC Bioinformatics",
    year = "2019",
    volume = "20",
    number = "1",
    pages = "1--17",
    doi = "10.1186/s12859-019-2942-y",
    URL = "https://doi.org/10.1186/s12859-019-2942-y"
  ),
  ishwaran2014rsf = bibentry("article",
    title = "Random survival forests for competing risks",
    author = "Ishwaran, H. and Gerds, T. A. and Kogalur, U. B. and Moore, R. D. and Gange, S. J. and Lau, B. M.",
    journal = "Biostatistics",
    year = "2014",
    volume = "15",
    number = "4",
    pages = "757--773",
    doi = "10.1093/BIOSTATISTICS/KXU010",
    URL = "https://doi.org/10.1093/BIOSTATISTICS/KXU010"
  )
) # nolint end
