# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_Akritas <- function(truth, times, unique_times, FX_train, FX_predict, lambda) {
    .Call(`_mlr3extralearners_C_Akritas`, truth, times, unique_times, FX_train, FX_predict, lambda)
}
