# r cmd check workflow of the mlr3 ecosystem v0.1.0
# https://github.com/mlr-org/actions
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: r-cmd-check-paradox

jobs:
  r-cmd-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'devel'}
          - {os: ubuntu-latest,   r: 'release'}

    steps:
      - uses: actions/checkout@v3

      - name: paradox
        run: 'sed -i "s|mlr-org/mlr3proba,|    mlr-org/paradox@s3_params,\n    mlr-org/mlr3learners@s3params_compat,\n    mlr-org/mlr3pipelines@s3params_compat,\n    mlr-org/mlr3proba@s3params_compat,\n    mlr-org/mlr3cluster@s3params_compat,|" DESCRIPTION'
      - name: debug
        run: cat DESCRIPTION

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
      - uses: r-lib/actions/check-r-package@v2
